name: Build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
      - run: ./gradlew build
      - run: ./gradlew nativeCompile
      - name: show results
        run: ls -lah build/native/nativeCompile && file build/native/nativeCompile/*

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: xcresults-macos-arm64
          path: build/native/nativeCompile/xcresults

